language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key: 
    secure: "KNIPn93/mnjau5bt7ip+mKsONRQzmNB+ubMF+ya94Zz+M+flckzqYqqrWt6IY2dOc34cpsFxhbenIGVhUPeprmfSFpn7y0eQAVZKGZv3Y9tNbiVE+dAwgkJuB8XhB1l8wRUZgAASx60FBatt4ymdPOcVOMrl1vB0EeWK5IX05KY4HcKGePc8TXOODWJrYGKzctSpbnPtCOp40s5VcsjyTf3BnZsHnrKC4KJGxZzJ2GPR+8kAYND/b8gIp9PhlNs4JFPKOR3wtPcAR628hn7p8ZiEHobJL5oRG/EqBkK0yNuUf/2RyDVYv2qXlcOL0jc5CwObO5GWJeazmTrpb8sw359lSSXzfaJ6k8yose5++EEPFVJTCaxopfT5eVRGhJh9x4Dg3b2Si7l6ML/o3CisumMUtLsb25y+ml2hpoIwqzM5xkjfjz5m26JfDxo/W2QfGbBwSH30fbRzXSDzvHYL3Ms5f9XFEIlDJ23Gzf35ITkI1QnzbYuU9WNaRWCG/uXnRi6FyNCuC+Xq/aj2ZwJwQZn6mqMaSomh+KqSTnAwgwtWTWhdo4JmMAAp9GjZVIBK0h6GLCE="
  on:
    repo: uva-cs3240-f20/project-1-02
