# Generated by Django 3.1.1 on 2020-11-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=20)),
                ('classNumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_passed_in', models.CharField(max_length=12)),
                ('password_passed_in', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default name', max_length=12)),
                ('firstname', models.CharField(default='Sammy', max_length=12)),
                ('lastname', models.CharField(default='Lahrime', max_length=12)),
                ('password', models.CharField(default=' ', max_length=12)),
                ('classes', models.CharField(default=' ', max_length=200)),
                ('description', models.CharField(default=' ', max_length=250)),
                ('userid', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
