# Generated by Django 3.1.1 on 2020-10-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_passed_in', models.CharField(max_length=12)),
                ('password_passed_in', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('postID', models.CharField(default=models.AutoField(primary_key=True), max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('firstname', models.CharField(default='Sammy', max_length=12)),
                ('lastname', models.CharField(default='Lahrime', max_length=12)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
