# Generated by Django 3.0.6 on 2020-11-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyForum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='na', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(default='na', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(default='na', max_length=20),
        ),
    ]
