# Generated by Django 3.1.1 on 2020-10-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyForum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='Sammy', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='Lahrime', max_length=12),
        ),
    ]
