# Generated by Django 3.1.1 on 2020-11-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyForum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discord_link',
            field=models.CharField(default='na', max_length=100),
        ),
    ]
