# Generated by Django 3.1.1 on 2020-10-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyForum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postID',
            field=models.CharField(default='12', max_length=100),
        ),
    ]
