# Generated by Django 3.1.1 on 2020-11-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyForum', '0002_auto_20201124_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='user_first',
            field=models.CharField(default='na', max_length=12),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user_last',
            field=models.CharField(default='na', max_length=12),
        ),
    ]
