# Generated by Django 3.1.1 on 2020-11-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyForum', '0002_post_discord_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='discord_link',
            field=models.CharField(default='na', max_length=100),
        ),
    ]
