# Generated by Django 3.0.6 on 2020-11-05 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyForum', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
    ]
