# Generated by Django 3.1.1 on 2020-11-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyForum', '0003_auto_20201109_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='somethingplease',
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default='computer science', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(default='third year', max_length=100),
        ),
    ]
