# Generated by Django 3.1.1 on 2020-11-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyForum', '0003_group_discord_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='phone',
            field=models.CharField(default='na', max_length=50),
        ),
    ]
