# Generated by Django 3.1.1 on 2020-11-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyForum', '0003_remove_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
