# Generated by Django 3.0.6 on 2020-11-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyForum', '0003_post_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
