# Generated by Django 3.0.6 on 2020-11-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyForum', '0004_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
