# Generated by Django 3.1.1 on 2020-11-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyForum', '0004_auto_20201124_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='na', max_length=100),
        ),
    ]
